async def list_parks(interaction, tree, guild=None):
 await interaction.response.defer()
 embed=discord.Embed(title="All parks available", url="https://themeparks.wiki", description="These are all parks currently registered", color=0x00ff88)
 embed.add_field(name="Guangzhou Chimelong Tourist Resort", value="Chimelong Paradise Chimelong Water Park Chimelong Safari Park Chimelong Birds Park", inline=True)
 embed.add_field(name="Walibi Holland", value="Walibi Holland", inline=True)
 embed.add_field(name="Parc Asterix", value="Parc Asterix", inline=True)
 embed.add_field(name="Plopsaland De Panne", value="Plopsaland De Panne", inline=True)
 embed.add_field(name="California's Great America", value="California's Great America", inline=True)
 embed.add_field(name="Europa-Park", value="Rulantica Europa-Park", inline=True)
 embed.add_field(name="Silver Dollar City", value="Silver Dollar City", inline=True)
 embed.add_field(name="Walibi Rhône-Alpes", value="Walibi Rhône-Alpes", inline=True)
 embed.add_field(name="Dollywood", value="Dollywood", inline=True)
 embed.add_field(name="Phantasialand", value="Phantasialand", inline=True)
 embed.add_field(name="Holiday Park", value="Holiday Park", inline=True)
 embed.add_field(name="Chimelong International Ocean Tourist Resort", value="Chimelong Spaceship Chimelong Ocean Kingdom", inline=True)
 embed.add_field(name="Hansa-Park", value="Hansa-Park", inline=True)
 embed.add_field(name="LEGOLAND Billund", value="LEGOLAND Billund", inline=True)
 embed.add_field(name="Walt Disney World® Resort", value="Magic Kingdom Park EPCOT Disney's Hollywood Studios Disney's Animal Kingdom Theme Park Disney's Typhoon Lagoon Water Park Disney's Blizzard Beach Water Park", inline=True)
 embed.add_field(name="Everland Resort", value="Caribbean Bay Everland", inline=True)
 embed.set_footer(text="page 1")
 await interaction.followup.send(embed)

 embed2=discord.Embed(title="All parks available", url="https://themeparks.wiki", description="These are all parks currently registered", color=0x00ff88)
 embed.add_field(name="and many more", value="7797976986y", inline=True)
 embed.set_footer(text="page 1")

 await interaction.followup.send(embed2)